

#
# User configuration sourced by interactive shells
#

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi


export GOPATH="/home/thomas/go"
export PATH="/home/thomas/pkgdiff/:/home/thomas/bin/:/home/thomas/smartgit/bin/:/home/thomas/p4/bin/:/home/thomas/tortoisehg/:/home/thomas/maven/bin:/home/thomas/intellij/bin:/home/thomas/pycharm/bin:/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/thomas/go/bin:$GOPATH/bin"

alias zshrc="emacs ~/.zshrc"
alias src="source ~/.zshrc"
alias tcstart="~/tomcat/bin/catalina.sh jpda start > /dev/null"
alias tcsl="tcstart && tclog"
alias tcstop="~/tomcat/bin/catalina.sh stop 4 -force"
alias tclog="tail -f ~/tomcat/logs/catalina.out"
alias tcclearlogs="rm -f ~/tomcat/logs/*"
alias tl="~/tomcat/logs"
alias wa="~/tomcat/webapps"
alias psc="ps aux | grep catalina"
alias grh="git reset --hard HEAD"
alias tf="tail -f"
alias gb="git blame"
alias gst="git status"
alias gf="git fetch --prune origin"
alias gp="git pull"
alias gs="git status"
alias gd="git diff"
alias lc="less ~/tomcat/logs/catalina.out"
alias cls="clear"
alias glsd="git log --pretty=format:'%Cgreen(%cd) %Creset %Cred%h%Creset -%C(yellow)%d%Creset %s %C(bold blue)%cn' --date=short"
alias glld="git log --pretty=format:'%Cgreen(%cd) %Creset %Cred%h%Creset -%C(yellow)%d%Creset %s %C(bold blue)%cn' --date=local"
alias ll="ls -la"
alias gitme="git log --pretty=format:'%Cred%H%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)' --author=thomas.junk@intevation.de"
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias gshow="git show"
alias sep="echo '------------------->'"
alias me="whoami"
alias pc4="ping -c4 "
alias genpass="tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c"
alias i3rc="emacs ~/.config/i3/config"
alias a="source env/bin/activate 2> /dev/null || source ../env/bin/activate"
alias x="chmod u+x"
alias hgrc='emacs ~/.hgrc'
alias ux='chmod u+x'
alias hi="hg in"
alias ho="hg out"
alias hd="hg diff"
alias hs="hg status"
alias hf="hg pull -u"
alias hh="hg tags | head"
alias hu="hg update"
alias hl="hg glog"
alias h="hg glog -l1"
alias b="hg branch"
alias bb="hg branches"
alias hgs="hg serve"
alias hrh="hg revert -a"
alias docs="invoke docs && serve"
alias waskiq="cd ~/Intevation/waskiq/"
alias sib="cd ~/Intevation/sib/"
alias pwe="cd ~/Intevation/pwe/"
alias ec="cd ~/Intevation/ec/"
alias qe="cd ~/Intevation/qe/"
alias ringo="cd ~/Intevation/lib/ringo"
alias reportserver="cd ~/Intevation/reportserver"
alias efa="cd ~/Intevation/lib/efa"
alias formbar="cd ~/Intevation/lib/formbar"
alias brabbel="cd ~/Intevation/lib/brabbel"
alias aspirant="cd ~/Intevation/lib/aspirant"
alias euhu="cd ~/Intevation/lib/euhu"
alias ecimporter="cd ~/Intevation/ecimporter"
alias bewec="cd ~/Intevation/bewec"
alias p="pserve development.ini --reload"
alias psetup="python setup.py develop"
alias termrc="emacs ~/.config/termite/config"
alias admin="~/smart-admin.sh"
alias dbreset="~/dbreset.sh"
alias thoe="ssh thoe"
alias wdev="ssh waskiqdev"
alias tunnel="ssh tjunk@thoe.intevation.de -L 5000:sib-testing.hq.intevation.de:80 -N"
alias trc="emacs /home/thomas/.config/termite/config"
alias s="python -m SimpleHTTPServer"
alias intevation="cd /home/thomas/Intevation"
alias misc="~/misc"
alias side="cdiff -s0"
alias hsrm="hs | cut -d " " -f2 | xargs rm"
alias sublime="/bin/sublime_text"
alias runserver="python manage.py runserver"
alias awrc="emacs /home/thomas/.config/awesome/rc.lua"
export TERM="xterm-256color"
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
alias images="docker images"
alias image="docker image"
alias container="docker container"
alias dps="docker ps -a"
alias smartgit="smartgit.sh"
alias syu="sudo zypper up"
eval $(dircolors ~/.dircolors)
export PANEL_FIFO="/tmp/panel-fifo"
alias emacs="emacs -nw"
 . /etc/profile.d/vte.sh
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
setopt clobber
alias release="emacs /home/thomas/workspace/emacs/org/releases/releases.org"
alias emacsrc="emacs ~/.emacs.d/init.el"
alias r="rails server -b 127.0.0.1 -p 8000"
alias mkinit="touch __init__.py"
