#! /bin/sh

sxhkd &
compton &
dunst &
nm-applet &
dropbox start &
polybar main &
setxkbmap -layout de &
~/gnomekeyring.sh &

feh --bg-scale ~/Bilder/pferdekopf.jpg 

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         0
bspc config window_gap           8
bspc config split_ratio          0.52
bspc config single_monocle                true
bspc config borderless_monocle            true
bspc config gapless_monocle               true

bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true

bspc rule -a Gimp desktop='^8' state=floating follow=on 
bspc rule -a Pidgin desktop='^8'
bspc rule -a Google-chrome desktop='^1'
bspc rule -a Code desktop='^3'
bspc rule -a Emacs desktop='^3'
bspc rule -a Atom desktop='^3'
bspc rule -a Nautilus desktop='^5'
bspc rule -a Thunderbird desktop='^7'
bspc rule -a net-sourceforge-squirrel_sql-client-Main desktop='^6'
bspc rule -a jetbrains-pycharm-ce desktop='^4'

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


